version: '3'

vars:
  GOOS: "{{default OS .GOOS}}"
  MVNW: '{{if eq .GOOS "windows"}}mvnw.cmd{{else}}./mvnw{{end}}'
  DC_DIR: "deployment/docker-compose"
  INFRA_DC_FILE: "{{.DC_DIR}}/infra.yml"

tasks:
  default:
    cmds:
      - task: test
  test:
    deps: [format]
    cmds:
      - "{{.MVNW}} clean verify"

  format:
    cmds:
      - "{{.MVNW}} spotless:apply"

  build:
    cmds:
      - "{{.MVNW}} verify"

  start_infra:
    cmds:
      - docker compose -f "{{.INFRA_DC_FILE}}" up -d

  stop_infra:
    cmds:
      - docker compose -f "{{.INFRA_DC_FILE}}" stop
      - docker compose -f "{{.INFRA_DC_FILE}}" rm -f

  restart_infra:
    cmds:
      - task: stop_infra
      - task: sleep
      - task: start_infra

  sleep:
    vars:
      DURATION: '{{default 5 .DURATION}}'
    cmds:
      - sleep {{.DURATION}}